version: "3.7"

services:
  testDb:
    container_name: test-db
    image: mysql:8.0.31
    restart: always
#    platform: linux/x86_64/v8
    ports:
      - "13307:3306"
    environment:
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql.d/:/docker-entrypoint-initdb.d